"""shorturl table

Revision ID: d7d51a76eb11
Revises: 
Create Date: 2020-11-13 00:20:15.745976

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'd7d51a76eb11'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shortURL',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=True),
    sa.Column('short', sa.String(length=8), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shortURL_short'), 'shortURL', ['short'], unique=True)
    op.create_index(op.f('ix_shortURL_url'), 'shortURL', ['url'], unique=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_shortURL_url'), table_name='shortURL')
    op.drop_index(op.f('ix_shortURL_short'), table_name='shortURL')
    op.drop_table('shortURL')
    # ### end Alembic commands ###
